### PR TITLE
Visualize updates

### PR DESCRIPTION
**Pull request by msleckman**
**Changes added through this PR:**
* Updated structure and separated out some stand alone functions
* defined additional vectors, and new sub-folders in `_targets.R` 
* Added bar plot function `stacked_bar_plot()` to create bar plot instead of timeline change 
image

* incorporated barplot() into the ggplot frame 

* reduced downsample to 8. Will reduced further if possible. 
image

**To do's:** 
- [x]  Decide on level plot or ggplot option - _going for for ggplot but levelplot output serves a way to qc. Also quick. 
- [x] Incorporate stacked_bar_plot() into the `raster_plotting_w_ggplot()` - _done, substituted the geom_line/geom_point with geom_bar()_

- [x] Figure out how to only show one of the bars with each map output 
 --> Not so good with using tar_map() and I am unsure how to make this such that the single bar plot can appear when the map of that year is.shows. 
- [x] Figure out how to make a gif out of ggplot outputs 
--> currently not creating gif when I run the following target: `p3_animate_ggplots_frames_gif`
- [x] Add year to map output 
- [x] remove dark water from legend (open ocean and rivers not visible here).  
- [x] Change background col (@ceenell ?)
Issue: 
- target `p3_save_map_frames_ggplot` not functioning properly. Getting same map output for every year output.

### CODE REVIEW

**Comment by hcorson-dosch-usgs** [comment]
Documenting my responses from our chat on 4/25 and 4/26 so that we have them here for future reference.

I think the quickest way to address the first issue w/ the area plots is to map over the gif years, like so:
```r
tar_target(
    p3_gif_years,
    c('1900','1910','1920','1930','1940','1950','1960','1970','1980','1990','2001','2011','2019')
),
## create ggplot visual - Cee inspo!!!
tar_target(
    p3_save_map_frames_ggplot,
    raster_ploting_w_ggplot(
        raster_in = p2_downsamp_raster_list,
        reach_shp = p1_streams_polylines_drb,
        counts = p2_raster_cell_count,
        chart_year = p3_gif_years,
        legend_df = legend_df,
        title = "NLCD in the DRB",
        font_fam = "Dongle", out_folder = '3_visualize/out/ggplots/'),
    pattern = map(p2_downsamp_raster_list, p3_gif_years),
    format = "file",
),
```
Then in raster_ploting_w_ggplot(), add a new argument chart_year and filter to that year
```r
raster_ploting_w_ggplot <- function(raster_in, reach_shp, counts, chart_year, legend_df, title, font_fam = "Source Sans Pro", out_folder = "3_visualize/out"){
    ...
    # Area through time
    nlcd_area <- counts %>%
        # find % of total area in each category over time
        left_join(counts %>%
        group_by(rast)%>%
        summarize(total_cells = sum(count))) %>%
        mutate(year = as.numeric(stringr::str_sub(rast,-4,-1)),
        percent = count/total_cells) %>%
        filter(value != 0, year == chart_year) %>%
        ggplot(aes(year,
        percent,
        group = value,
        # color = factor(value),
        fill = factor(value))
        )+
````
The x-axis will need fixing, but seems to be working as expected:
image

**Comment by hcorson-dosch-usgs** [comment]
And for issue you noted that `p3_save_map_frames_ggplot` is outputting the same map image over and over, looks like that's because all of the rasters in `p2_downsamp_raster_list` are identical. The `p2_reclassified_raster_list` rasters are all different, so I took a look at `downsamp_cat()` and it looks like you maybe accidentally left some testing code in there? [These lines](https://github.com/msleckman/chart-challenge-22/blob/visualize_updates/23_tiles_msleckman/2_process/src/downsampling.R#L5-L6) are setting the variable raster in that function to be the first raster (1900) every time, rather than the unique raster that's actually being passed when `targets` builds `p2_downsamp_raster_list`. So I think your code will work as expected if you delete those two lines.

I tested it and looks like it worked:
image
image

One note - I also dropped the `[[1]]` subsetting [here](https://github.com/msleckman/chart-challenge-22/blob/visualize_updates/23_tiles_msleckman/2_process.R#L63-L64) because it looked like you were subsetting within `downsamp_raster_cat()` [here](https://github.com/msleckman/chart-challenge-22/blob/visualize_updates/23_tiles_msleckman/2_process/src/downsampling.R#L7). 
** EDITED TO ADD ** - Margaux tested this and we realized this only works if you _have_ implemented list iteration. If not using list iteration, this subsetting needs to stay

Also - this would be an optional change, but added list iteration to your `p2` raster list targets since you had them named as lists:
image

**Comment by hcorson-dosch-usgs** [comment]
Then re:

 > Figure out how to make a gif out of ggplot outputs
--> currently not creating gif when I run the following target: p3_animate_ggplots_frames_gif

I think that can be fixed by

a) returning the filenames from `raster_plotting_w_ggplot()`:
image

and b) referencing the `p3_save_map_frames_ggplot` target (with those returned filenames) when building `p3_animate_ggplots_frames_gif`:
image

**Comment by cnell-usgs** [comment]
To add the white background to the plot, in `raster_plotting_w_ggplot.R` add:
```   
canvas <- rectGrob(
  x = 0, y = 0, 
  width = 16, height = 9,
  gp = gpar(fill = "white", alpha = 1, col = 'white')
)

# combine plot elements
ggdraw(ylim = c(0,1), xlim = c(0,1)) +
  # a white background
  draw_grob(canvas,
            x = 0, y = 1,
            height = 9, width = 16,
            hjust = 0, vjust = 1)+
```

**Pull request merged**
